# Generated by Django 5.0.6 on 2024-08-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subusers',
            name='user_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
