# Generated by Django 5.0.6 on 2024-08-12 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0002_alter_subusers_user_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='subusers',
            managers=[
            ],
        ),
    ]
