# Generated by Django 5.0.6 on 2024-08-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0003_alter_subusers_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_test', models.CharField(max_length=100)),
            ],
        ),
    ]
