# Generated by Django 5.0.6 on 2024-08-13 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0004_movie_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie_Test',
        ),
    ]
