# Generated by Django 5.0.6 on 2024-08-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0005_delete_movie_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subusers',
            name='expiry',
            field=models.DateField(null=True),
        ),
    ]
