# Generated by Django 5.0.6 on 2024-08-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0006_alter_subusers_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='subusers',
            name='token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
