# Generated by Django 5.0.6 on 2024-08-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0007_subusers_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subusers',
            name='token',
        ),
    ]
