# Generated by Django 5.0.6 on 2024-08-14 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0008_remove_subusers_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subusers',
            name='random_key',
            field=models.BigIntegerField(null=True),
        ),
    ]
