# Generated by Django 5.0.6 on 2024-08-20 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0011_alter_subusers_random_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='watch_latter',
            new_name='watch_later',
        ),
    ]
